language: csharp
solution: CoderDocTools.sln
mono:
- latest
install:
- nuget restore CoderDocTools.sln
- nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
- msbuild /p:Configuration=Release CoderDocTools.sln
- mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/XUnit/bin/Release/net461/MarkdownToPDFTests.dll