language: csharp
solution: GitHubWikiToPDF.sln
install:
- nuget restore GitHubWikiToPDF.sln
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
- msbuild /p:Configuration=Release GitHubWikiToPDF.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./tests/ParsingTests/bin/Release/netcoreapp2.1/ParsingTests.dll